name: Simple Shell Command

on: [push]

jobs: 
  run-powershell-command:
    runs-on: windows-latest
    steps:
      - name: Download vctl
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/patrodisbx/gitaction/development/vctl/vctl.exe -Outfile ./vctl.exe

      - name: list all files
        run: dir

      - name: login to vctl
        run: D:/a/gitaction/gitaction/vctl.exe login https://vsystem.ingress.dh-ifc1k6ng.di-us-east.shoot.live.k8s-hana.ondemand.com disbxt01 DIAPIUSR -p DI@apiuser123


      