name: Simple Shell Command

on: [push]

jobs: 
  run-powershell-command:
    runs-on: windows-latest
    steps:
      - name: Download vctl
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/patrodisbx/gitaction/development/vctl/vctl.exe -Outfile ./vctl.exe

      - name: list all files
        run: dir


      